//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaInfo
    {
        public int AreaID { get; set; }
        public int AreaTypeID { get; set; }
        public string AreaName { get; set; }
        public string AreaReMark { get; set; }
    
        public virtual AreaTypeInfo AreaTypeInfo { get; set; }
    }
}
