//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetDetailRecordInfo
    {
        public int AssetDetailRecordID { get; set; }
        public int AssetDetailID { get; set; }
        public int EmpolyID { get; set; }
        public int AreaID { get; set; }
        public int AssetNum { get; set; }
        public System.DateTime AssetDetailRecordUseDate { get; set; }
        public Nullable<System.DateTime> AssetDetailRecordReturnDate { get; set; }
        public string AssetDetailRecordReMark { get; set; }
    }
}
