//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetPutInfo
    {
        public int AssetPutID { get; set; }
        public Nullable<int> AssetID { get; set; }
        public int AssetPutCount { get; set; }
        public System.DateTime AssetPutDate { get; set; }
        public Nullable<int> EmpolyID { get; set; }
        public string AssetPutReMark { get; set; }
    
        public virtual AssetInfo AssetInfo { get; set; }
    }
}
