//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpolyInfo
    {
        public int EmpolyID { get; set; }
        public string EmpolyNum { get; set; }
        public string EmpolyPwd { get; set; }
        public string EmpolyName { get; set; }
        public string EmpolySex { get; set; }
        public string EmpolyldCard { get; set; }
        public string Empolylmg { get; set; }
        public Nullable<int> DeptID { get; set; }
        public int EmpolyLevel { get; set; }
        public int RoleID { get; set; }
        public Nullable<System.DateTime> InductionDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string EmpolyReMark { get; set; }
    
        public virtual DeptInfo DeptInfo { get; set; }
        public virtual RoleInfo RoleInfo { get; set; }
    }
}
