//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeSuppliesRecordInfo
    {
        public int OfficeID { get; set; }
        public int AssetID { get; set; }
        public int OfficeApplylD { get; set; }
        public int OfficeApplyNum { get; set; }
        public int OfficeApplyState { get; set; }
        public System.DateTime OfficeApplyDate { get; set; }
        public Nullable<int> OfficeReceiveNum { get; set; }
        public Nullable<System.DateTime> OfficeReceiveDate { get; set; }
        public string OfficeRemark { get; set; }
    }
}
